name: Import Project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install gdown
        run: pip install gdown

      - name: Download Project
        run: |
          gdown 1csNSMjgN3K9AaZ9_MY0uRkroFsIwitfZ -O project.zip

      - name: Extract
        run: unzip -o project.zip

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "Import project" || echo "No changes"

          git branch
          git remote -v

          git push origin HEAD:main
